framework:
    secret: "Three can keep a secret, if two of them are dead."
    templating:
        engines: [twig]
    profiler:
        enabled: %kernel.debug%

doctrine:
    dbal:
        driver: pdo_sqlite
        path: %kernel.root_dir%/db.sql
        charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    domain:
                        type: yml
                        prefix: App\Domain
                        dir: "%kernel.root_dir%/config/doctrine"
                        is_bundle: false
